.\"	$NetBSD$
.\"
.\" Copyright (c) 2019 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Kamil Rytarowski.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 6, 2019
.Dt PICOTRACE 1
.Os
.Sh NAME
.Nm picotrace
.Nd system call process tracer
.Sh SYNOPSIS
.Nm
.Ar [ -i] [-o OUTPUT] [-p PID | <command> [<arg ...>]]
.Sh DESCRIPTION
.Nm
enables syscall trace logging for the specified processes.
Trace data is logged to the file
.Pa OUTPUT ,
otherwise if not specified to
.Pa stdout .
The operations that are traced include system call entry and exit,
signal delivery, forking, vforking, LWP creation, LWP exiting and
process exiting.
Additionally
.Nm
logs arguments passed to a program,
environment variables and ELF auxiliary vector values.
.Pp
Once tracing is enabled on a process, trace data will be logged until
either the process exits or the trace point is cleared.
A traced process can generate large amounts of log data quickly.
.Pp
The trace output is in plain text, human readable.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl i
Inherit; pass the trace flags to all future children of the designated
processes.
.It Fl o Ar OUTPUT
Log trace records to
.Ar outfile .
Without this option
.Nm
will print its output to standard output.
.It Fl p Ar PID
Enable (disable) tracing on the indicated process id (only one
.Fl p
flag is permitted).
.It Ar command
Execute
.Ar command
with the specified trace flags.
.El
.Pp
The
.Fl p
and
.Ar command
options are mutually exclusive.
.Sh OUTPUT FORMAT
The output is grouped into 5 columns:
.Bl -tag -width indent
.It pid
Traced process id.
.It lwp
Traced process LWP that caused an event.
The 0 value is a special case for whole-process events.
.It exename
Traced process program basename.
.It event
Recorded event:
.Bl -tag -width indent
.It ARGV
Field in the argv[] vector.
.It ENV
Field in the env[] vector.
.It AUXV
Field in the auxv[] vector.
.It SCE
System call entry.
.It SCX
System call exit.
.It CONTINUED
The process has been continued with SIGCONTINUE.
.It SIGNALED
The process has received non-stoppable signal.
.It EXITED
The process has exited.
.It EXEC
The process has replaced its process image with a new process image.
.It FORKED
The process has forked.
.It VFORKED
The process has vforked.
.It VFORK_DONE
The process has resumed after
.Xr vfork 2 .
.It LWP_CREATED
The process has created a thread.
.It LWP_EXITED
The process has exited a thread.
.It CRASHED
The process has crashed.
.It STOPPED
The process has stopped
.El
.It additional information
If available, extra pieces of information.
.Sh EXAMPLES
# trace the events of process id 34
.Dl $ picotrace -p 34
.Pp
# spawn and trace process sh(1) with all of its children and log the
record to "trace.txt"
.Dl $ picotrace -o "trace.txt" -i sh
.Sh IMPLEMENTATION NOTES
The tracer uses the
.Xr ptrace 2
system call to perform the tracing process.
.Pp
The
.Nm
program has been designd to ship bare functionality only,
without pretty printing of data structures and interpreting passed
arguments to syscalls.
.Pp
.Nm
is designed to be a framework for other more advanced tracers and
illustration of the canonical usage of the
.Xr ptrace
system call.
New features are not expected unless they present a new feature in the
.Nx
kernel.
.Sh SEE ALSO
.Xr ktruss 1 ,
.Xr ptrace 2
.Sh HISTORY
.Nm
is inspired by
.Nm truss
from
.Fx
and
.Nm strace
from Linux.
.Pp
Tn
.Nm
command was designed for
.Nx 9 .
.Sh AUTHORS
.An Kamil Rytarowski Aq Mt kamil@NetBSD.org
